import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = Options()
options.add_experimental_option("debuggerAddress", "127.0.0.1:9527")

driver=webdriver.Chrome(options=options)

#進入要搶的咖啡頁面
driver.get('https://shopee.tw/POP-MART-%E6%B3%A1%E6%B3%A1%E7%91%AA%E7%89%B9-%E5%A4%A9%E7%B7%9A%E5%AF%B6%E5%AF%B6%E6%BD%AE%E6%B5%81%E6%89%8B%E8%BE%A6-i.458623340.25536438392?sp_atk=46acc7ff-952d-4a11-993a-48b757809315&xptdk=46acc7ff-952d-4a11-993a-48b757809315')

#最大等待時間設定為5分鐘(300秒)，等"直接購買"avaliable後點選
def do():
    WebDriverWait(driver, 300).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[class='btn btn-solid-primary btn--l rvHxix']"))).click()
    print('------do')

#等"去買單"avaliable後點選，需強制睡一秒最順
def do2():
    time.sleep(1)
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[class='shopee-button-solid shopee-button-solid--primary']"))).click()
    print('-----do2')

#等"貨到付款"avaliable後點選
def do3():
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[aria-label='信用卡']"))).click()
    print('-----do3')

#等"下訂單"avaliable後點選
def do4():
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[class='stardust-button stardust-button--primary stardust-button--large _1qSlAe']"))).click()
    print('-----do4')

#測試先關掉最後"下訂單"
do()
do2()
do3()
# do4()
